name:                useragent
version:             0.1.0.0
github:              "jiayuanmark/useragent"
license:             BSD3
author:              "Jiayuan Ma"
maintainer:          "jiayuanmark@gmail.com"
copyright:           "Jiayuan Ma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jiayuanmark/useragent#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- containers
- bytestring

library:
  source-dirs: src

executables:
  useragent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - useragent

tests:
  useragent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - useragent
